from types import FunctionType

from .function_definitions import (
    abbreviate,
    add,
    boolean,
    case,
    copy,
    divide,
    first,
    hide,
    last,
    match,
    multiply,
    rand,
    repeat,
    reverse,
    save,
    separator,
    subtract,
    sync,
)

function_definitions: dict[str, FunctionType] = {
    "abbr": abbreviate,
    "abbreviate": abbreviate,
    "add": add,
    "bool": boolean,
    "case": case,
    "copy": copy,
    "divide": divide,
    "div": divide,
    "first": first,
    "hide": hide,
    "last": last,
    "match": match,
    "multiply": multiply,
    "mul": multiply,
    "prod": multiply,
    "rand": rand,
    "rep": repeat,
    "reverse": reverse,
    "save": save,
    "sep": separator,
    "subtract": subtract,
    "sub": subtract,
    "x": sync,
    "sync": sync,
}
